import { defineConfig } from 'orval';
import dotenv from 'dotenv';

dotenv.config();

// 공통으로 사용할 헤더 주석 (빌드 최적화의 핵심)
const buildOptimizationHeader = [
  '/* eslint-disable */',
  '// @ts-nocheck',
  '// This file is automatically generated by Orval.',
  '// Do not edit it manually.',
];

export default defineConfig({
  'fetch-api': {
    input: {
      target: process.env.SWAGGER_URL || 'http://localhost:8080/openapi.yaml',
    },
    output: {
      mode: 'tags-split',
      target: './src/api/generated',
      client: 'fetch',
      mock: true,
      clean: true,
      override: {
        // 모든 생성 파일 상단에 주석 주입
        header: () => buildOptimizationHeader,
        mutator: {
          path: './src/lib/custom-fetch.ts',
          name: 'customFetch',
        },
      },
    },
  },
  'zod-api': {
    input: {
      target: process.env.SWAGGER_URL || 'http://localhost:8080/openapi.yaml',
    },
    output: {
      mode: 'tags-split',
      client: 'zod',
      target: './src/api/zod',
      formatter: 'prettier',
      clean: true,
      override: {
        // Zod 생성 파일도 빌드 검사에서 제외
        header: () => buildOptimizationHeader,
      },
    },
  },
});
