/**
 * Figma 디자인(node-id=6402-27970)에는 케이스 태그·매장 의견·SLA 뱃지·결제금액과 분리된
 * 환불금액(위약금 %)·마스킹 전화번호·4단계 상태가 있지만, 실제 생성된 관리자 환불 API
 * (`ApiResponseAdminRefundPageDataContentItem`)는 이 필드들을 아직 제공하지 않는다.
 * 백엔드가 확장되기 전까지 디자인 그대로 화면을 먼저 구현하기 위한 목업 데이터.
 */
import type { RefundMockRow } from '../types';

export const REFUND_MOCK_ROWS: RefundMockRow[] = [
  {
    requestId: 'REF-2401',
    caseLabel: 'B-달성후',
    caseDescription: '달성 후 취소 (픽업 3일 초과)',
    customerName: '김**',
    customerPhone: '010-****-1234',
    productName: '베이글 10개 세트',
    storeName: '행복한베이커리',
    paymentAmount: 30000,
    refundAmount: 27000,
    penaltyLabel: '-10% 위약금',
    storeOpinion: '미제출',
    requestedAt: '2026-05-13 14:30',
    slaLabel: '2시간 초과',
    status: '검토대기',
  },
  {
    requestId: 'REF-2398',
    caseLabel: 'G-분쟁',
    caseDescription: '의의제기 처리 대기',
    customerName: '이**',
    customerPhone: '010-****-5678',
    productName: '마카롱 박스',
    storeName: '달콤한제과',
    paymentAmount: 35000,
    refundAmount: 35000,
    penaltyLabel: '전액 환불',
    storeOpinion: '의의제기',
    requestedAt: '2026-05-13 16:45',
    slaLabel: '23시간 남음',
    status: '처리중',
  },
  {
    requestId: 'REF-2395',
    caseLabel: 'D-미수령',
    caseDescription: '미수령 (픽업기한 초과)',
    customerName: '박**',
    customerPhone: '010-****-9012',
    productName: '크루아상 세트',
    storeName: '아침빵집',
    paymentAmount: 18000,
    refundAmount: 18000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-13 09:15',
    slaLabel: '6시간 초과',
    status: '검토대기',
  },
  {
    requestId: 'REF-2390',
    caseLabel: 'A-달성전',
    caseDescription: '달성 전 자유 취소',
    customerName: '최**',
    customerPhone: '010-****-3456',
    productName: '식빵 세트',
    storeName: '행복한빵집',
    paymentAmount: 12000,
    refundAmount: 12000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-12 11:20',
    slaLabel: null,
    status: '승인완료',
  },
  {
    requestId: 'REF-2387',
    caseLabel: 'C-사장귀책',
    caseDescription: '사장님 사정으로 인한 취소',
    customerName: '정**',
    customerPhone: '010-****-7890',
    productName: '도넛 박스',
    storeName: '달콤한아침',
    paymentAmount: 20000,
    refundAmount: 20000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-11 18:05',
    slaLabel: null,
    status: '거절',
  },
];
