/**
 * Figma 디자인(node-id=6402-27970)에는 케이스 태그·매장 의견·SLA 뱃지·결제금액과 분리된
 * 환불금액(위약금 %)·마스킹 전화번호·4단계 상태가 있지만, 실제 생성된 관리자 환불 API
 * (`ApiResponseAdminRefundPageDataContentItem`)는 이 필드들을 아직 제공하지 않는다.
 * 백엔드가 확장되기 전까지 디자인 그대로 화면을 먼저 구현하기 위한 목업 데이터.
 */
import type { RefundMockRow } from '../types';

export const REFUND_MOCK_ROWS: RefundMockRow[] = [
  {
    requestId: 'REF-2401',
    caseLabel: 'B-달성후',
    caseDescription: '달성 후 취소 (픽업 3일 초과)',
    customerName: '김**',
    customerPhone: '010-****-1234',
    productName: '베이글 10개 세트',
    storeName: '행복한베이커리',
    storePhone: '010-****-1111',
    paymentAmount: 30000,
    refundAmount: 27000,
    penaltyLabel: '-10% 위약금',
    storeOpinion: '미제출',
    requestedAt: '2026-05-13 14:30',
    slaLabel: '2시간 초과',
    status: '검토대기',
    detail: {
      customerEmail: 'kim***@example.com',
      customerJoinMethod: '카카오',
      achieved: true,
      pickupDate: '2026-05-10',
      pickupLocation: '서울시 마포구 월드컵로 45',
      refundReason: '단순 변심',
      refundDescription:
        '픽업 기한(3일)이 지난 뒤 취소 요청이 접수되어 위약금 10%를 제외한 금액을 환불 대상으로 산정했습니다.',
      paymentMethod: '카드',
      approvalNumber: 'APV-20260508-2210',
      paidAt: '2026-05-08 10:12',
      storeOpinionSubmittedAt: null,
      storeOpinionContent: null,
      csTicketId: null,
      history: [
        {
          title: '환불 요청 접수',
          datetime: '2026-05-13 14:30',
          description: '소비자가 환불 요청 제출',
          tone: 'default',
        },
      ],
    },
  },
  {
    requestId: 'REF-2398',
    caseLabel: 'G-분쟁',
    caseDescription: '의의제기 처리 대기',
    customerName: '이**',
    customerPhone: '010-****-5678',
    productName: '마카롱 박스',
    storeName: '달콤한제과',
    storePhone: '010-****-5555',
    paymentAmount: 35000,
    refundAmount: 35000,
    penaltyLabel: '전액 환불',
    storeOpinion: '의의제기',
    requestedAt: '2026-05-13 16:45',
    slaLabel: '23시간 남음',
    status: '처리중',
    detail: {
      customerEmail: 'user***@example.com',
      customerJoinMethod: '카카오',
      achieved: true,
      pickupDate: '2026-05-18',
      pickupLocation: '서울시 강남구 테헤란로 123',
      refundReason: '상품 정보와 다름',
      refundDescription:
        '상품 설명에는 직경 5cm로 명시되어 있었으나, 실제 받은 제품은 3cm 정도로 크기가 작았습니다.',
      paymentMethod: '카드',
      approvalNumber: 'APV-20260512-1234',
      paidAt: '2026-05-12 15:30',
      storeOpinionSubmittedAt: '2026-05-13 18:20',
      storeOpinionContent:
        '상품 설명에 명시된 크기는 정확합니다. 소비자가 잘못 이해한 것으로 보입니다. 사진 첨부합니다.',
      csTicketId: 'CS-2398',
      history: [
        {
          title: '환불 요청 접수',
          datetime: '2026-05-13 16:45',
          description: '소비자가 환불 요청 제출',
          tone: 'default',
        },
        {
          title: '매장측 이의 제기',
          datetime: '2026-05-13 18:20',
          description: '사장님이 환불에 이의를 제기함',
          tone: 'default',
        },
        {
          title: 'CS 티켓 자동 생성',
          datetime: '2026-05-13 18:25',
          description: 'CS-2398 티켓 생성 완료',
          tone: 'warning',
        },
      ],
    },
  },
  {
    requestId: 'REF-2395',
    caseLabel: 'D-미수령',
    caseDescription: '미수령 (픽업기한 초과)',
    customerName: '박**',
    customerPhone: '010-****-9012',
    productName: '크루아상 세트',
    storeName: '아침빵집',
    storePhone: '010-****-3333',
    paymentAmount: 18000,
    refundAmount: 18000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-13 09:15',
    slaLabel: '6시간 초과',
    status: '검토대기',
    detail: {
      customerEmail: 'park***@example.com',
      customerJoinMethod: '이메일',
      achieved: true,
      pickupDate: '2026-05-11',
      pickupLocation: '서울시 종로구 자하문로 20',
      refundReason: '픽업 기한 내 미수령',
      refundDescription:
        '픽업 기한까지 매장을 방문하지 못해 상품을 수령하지 못했습니다. 전액 환불을 요청합니다.',
      paymentMethod: '카카오페이',
      approvalNumber: 'APV-20260509-7781',
      paidAt: '2026-05-09 08:40',
      storeOpinionSubmittedAt: '2026-05-13 10:05',
      storeOpinionContent: '미수령 확인했습니다. 환불에 동의합니다.',
      csTicketId: null,
      history: [
        {
          title: '환불 요청 접수',
          datetime: '2026-05-13 09:15',
          description: '소비자가 환불 요청 제출',
          tone: 'default',
        },
        {
          title: '매장 의견 제출',
          datetime: '2026-05-13 10:05',
          description: '사장님이 환불에 동의함',
          tone: 'default',
        },
      ],
    },
  },
  {
    requestId: 'REF-2390',
    caseLabel: 'A-달성전',
    caseDescription: '달성 전 자유 취소',
    customerName: '최**',
    customerPhone: '010-****-3456',
    productName: '식빵 세트',
    storeName: '행복한빵집',
    storePhone: '010-****-2222',
    paymentAmount: 12000,
    refundAmount: 12000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-12 11:20',
    slaLabel: null,
    status: '승인완료',
    detail: {
      customerEmail: 'choi***@example.com',
      customerJoinMethod: '애플',
      achieved: false,
      pickupDate: '2026-05-16',
      pickupLocation: '서울시 서대문구 연희로 8',
      refundReason: '단순 변심',
      refundDescription:
        '공구 달성 전 자유 취소 요청으로, 위약금 없이 전액 환불 대상입니다.',
      paymentMethod: '카드',
      approvalNumber: 'APV-20260512-0091',
      paidAt: '2026-05-12 09:02',
      storeOpinionSubmittedAt: '2026-05-12 11:40',
      storeOpinionContent: '달성 전 취소 확인했습니다. 환불에 동의합니다.',
      csTicketId: null,
      history: [
        {
          title: '환불 요청 접수',
          datetime: '2026-05-12 11:20',
          description: '소비자가 환불 요청 제출',
          tone: 'default',
        },
        {
          title: '매장 의견 제출',
          datetime: '2026-05-12 11:40',
          description: '사장님이 환불에 동의함',
          tone: 'default',
        },
        {
          title: '환불 승인 완료',
          datetime: '2026-05-12 13:10',
          description: '관리자가 환불을 승인하고 PG 환불을 실행함',
          tone: 'default',
        },
      ],
    },
  },
  {
    requestId: 'REF-2387',
    caseLabel: 'C-사장귀책',
    caseDescription: '사장님 사정으로 인한 취소',
    customerName: '정**',
    customerPhone: '010-****-7890',
    productName: '도넛 박스',
    storeName: '달콤한아침',
    storePhone: '010-****-4444',
    paymentAmount: 20000,
    refundAmount: 20000,
    penaltyLabel: '전액 환불',
    storeOpinion: '동의',
    requestedAt: '2026-05-11 18:05',
    slaLabel: null,
    status: '거절',
    detail: {
      customerEmail: 'jung***@example.com',
      customerJoinMethod: '카카오',
      achieved: false,
      pickupDate: '2026-05-15',
      pickupLocation: '서울시 용산구 이태원로 55',
      refundReason: '매장 사정으로 인한 취소',
      refundDescription:
        '매장 사정으로 공구가 취소되어 소비자 귀책 없이 전액 환불이 요청되었습니다.',
      paymentMethod: '카드',
      approvalNumber: 'APV-20260510-4420',
      paidAt: '2026-05-10 19:55',
      storeOpinionSubmittedAt: '2026-05-11 18:30',
      storeOpinionContent: '매장 사정으로 취소되었음을 확인했습니다.',
      csTicketId: null,
      history: [
        {
          title: '환불 요청 접수',
          datetime: '2026-05-11 18:05',
          description: '소비자가 환불 요청 제출',
          tone: 'default',
        },
        {
          title: '매장 의견 제출',
          datetime: '2026-05-11 18:30',
          description: '사장님이 환불에 동의함',
          tone: 'default',
        },
        {
          title: '환불 거절 처리',
          datetime: '2026-05-11 20:15',
          description: '중복 신청 건으로 확인되어 관리자가 거절 처리함',
          tone: 'default',
        },
      ],
    },
  },
];
