/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * 뭉치장 API
 * 유행 음식 공동구매 플랫폼 뭉치장의 API 명세입니다.

## 인증
로그인이 필요한 API는 `Authorization: Bearer {accessToken}` 헤더를 포함해야 합니다.

## 공통 응답 형식
모든 응답은 아래 구조를 따릅니다.
```json
{ "success": true, "data": { ... }, "error": null }
{ "success": false, "data": null, "error": { "code": "ERROR_CODE", "message": "설명", "detail": "상세" } }
```

 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

/**
 * @summary 알림 목록 조회
 */
export const getApiV1NotificationsQueryCategoryDefault = `ALL`;
export const getApiV1NotificationsQueryPageDefault = 0;
export const getApiV1NotificationsQuerySizeDefault = 20;
export const getApiV1NotificationsQuerySizeMax = 100;

export const GetApiV1NotificationsQueryParams = zod.object({
  category: zod
    .enum(['ALL', 'WISHLIST', 'PARTICIPATION', 'PICKUP', 'REQUEST'])
    .default(getApiV1NotificationsQueryCategoryDefault),
  page: zod.number().default(getApiV1NotificationsQueryPageDefault),
  size: zod
    .number()
    .max(getApiV1NotificationsQuerySizeMax)
    .default(getApiV1NotificationsQuerySizeDefault),
});

export const GetApiV1NotificationsResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    content: zod.array(
      zod.object({
        id: zod.number(),
        category: zod.enum(['WISHLIST', 'PARTICIPATION', 'PICKUP', 'REQUEST']),
        type: zod.enum([
          'PICKUP_TODAY',
          'PICKUP_TOMORROW',
          'PICKUP_NOT_CONFIRMED',
          'WISHLIST_DEADLINE_D3',
          'WISHLIST_DEADLINE_D1',
          'WISHLIST_TARGET_ACHIEVED',
          'PARTICIPATION_CONFIRMED',
          'GROUP_BUY_ACHIEVED',
          'GROUP_BUY_FAILED',
          'REQUEST_OPENED',
          'REQUEST_REJECTED',
          'REQUEST_NEW_PARTICIPANT',
          'REQUEST_TARGET_ACHIEVED',
          'REQUEST_DEADLINE_D3',
        ]),
        title: zod.string(),
        body: zod.string(),
        targetType: zod
          .enum(['GROUP_BUY', 'GROUP_BUY_REQUEST', 'PARTICIPATION'])
          .nullable(),
        targetId: zod.number().nullable(),
        isRead: zod.boolean(),
        readAt: zod.iso.datetime({ offset: true }).nullable(),
        actionType: zod
          .enum([
            'QR_CODE',
            'PICKUP_GUIDE',
            'GROUP_BUY_DETAIL',
            'MY_PAGE_ACTIVE',
            'MY_PAGE_REFUND',
            'REQUEST_STATUS',
          ])
          .nullable()
          .describe('인라인 액션 버튼 유형. null이면 버튼 미노출'),
        dateGroup: zod
          .enum(['TODAY', 'YESTERDAY', 'BEFORE'])
          .describe('알림 날짜 그룹 (오늘\/어제\/이전)'),
        createdAt: zod.iso.datetime({ offset: true }),
      }),
    ),
    totalElements: zod.number(),
    totalPages: zod.number(),
    number: zod.number(),
    size: zod.number(),
  }),
  error: zod.unknown().nullable(),
});

/**
 * @summary 미읽음 알림 개수 조회 (탭바 배지용)
 */
export const GetApiV1NotificationsUnreadCountResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    count: zod.number(),
  }),
  error: zod.unknown().nullable(),
});

/**
 * @summary 전체 알림 읽음 처리
 */
export const PatchApiV1NotificationsReadAllResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});

/**
 * @summary 개별 알림 읽음 처리
 */
export const PatchApiV1NotificationsNotificationIdReadParams = zod.object({
  notificationId: zod.number(),
});

export const PatchApiV1NotificationsNotificationIdReadResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});
