/* /* eslint-disable *\/ */
/**
 * // @ts-nocheck
 * // This file is automatically generated by Orval.
 * // Do not edit it manually.
 */
import * as zod from 'zod';

/**
 * @summary 공구 참여 (결제 요청 생성)
 */
export const PostApiV1GroupBuysGroupBuyIdParticipationsParams = zod.object({
  groupBuyId: zod.number(),
});

export const postApiV1GroupBuysGroupBuyIdParticipationsBodyAgreedTermsMin = 4;

export const PostApiV1GroupBuysGroupBuyIdParticipationsBody = zod.object({
  quantity: zod.number().min(1),
  agreedTerms: zod
    .array(
      zod.enum([
        'NO_CANCEL_AFTER_ACHIEVED',
        'FULL_REFUND_BEFORE_ACHIEVED',
        'NO_REFUND_IF_NOT_PICKED_UP',
        'NO_WITHDRAWAL_RIGHT',
      ]),
    )
    .min(postApiV1GroupBuysGroupBuyIdParticipationsBodyAgreedTermsMin)
    .describe('4개 항목 모두 포함 필수'),
});

/**
 * @summary PG 결제 성공 콜백 처리
 */
export const PostApiV1PaymentsConfirmBody = zod
  .object({
    paymentId: zod
      .uuid()
      .describe(
        '포트원 결제 ID (클라이언트가 UUID로 생성하여 SDK 호출 시 사용한 값)',
      ),
    participationId: zod.number(),
    amount: zod
      .number()
      .describe('결제 요청 금액 — 서버 저장값과 불일치 시 위변조로 처리'),
  })
  .describe(
    '포트원 v2 + 토스페이먼츠 결제 성공 후 서버 검증 요청.\n클라이언트가 PortOne.requestPayment() 완료 시 반환된 paymentId를 전달한다.\n서버는 포트원 API(GET \/payments\/{paymentId})로 위변조 검증 후 확정 처리한다.\n',
  );

export const PostApiV1PaymentsConfirmResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});

/**
 * @summary PG 결제 실패 콜백 처리
 */
export const PostApiV1PaymentsFailBody = zod
  .object({
    paymentId: zod.uuid().describe('포트원 결제 ID'),
    participationId: zod.number(),
    errorCode: zod.string().describe('포트원\/토스페이먼츠 오류 코드'),
    message: zod.string().nullable().describe('오류 메시지'),
  })
  .describe('포트원 v2 결제 실패\/취소 콜백 처리');

export const PostApiV1PaymentsFailResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});

/**
 * 공구 달성 전에만 취소 가능하며 결제 금액이 자동 환불된다.
 * @summary 참여 취소 (달성 전 이탈)
 */
export const PostApiV1ParticipationsParticipationIdCancelParams = zod.object({
  participationId: zod.number(),
});

export const PostApiV1ParticipationsParticipationIdCancelResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});

/**
 * @summary 내 환불 내역 조회
 */
export const GetApiV1RefundsResponse = zod.object({
  success: zod.boolean(),
  data: zod.array(
    zod.object({
      participationId: zod.number(),
      productName: zod.string(),
      storeName: zod.string(),
      pickupDate: zod.iso.date().nullable(),
      pickupTimeStart: zod.iso.time({}).nullable(),
      pickupTimeEnd: zod.iso.time({}).nullable(),
      paymentAmount: zod.number(),
      quantity: zod.number(),
      refundStatus: zod
        .enum(['PENDING', 'COMPLETED'])
        .describe('PENDING=환불대기 \/ COMPLETED=환불완료'),
      cancelReason: zod
        .enum(['NOT_ACHIEVED', 'EARLY_EXIT', 'PAYMENT_ERROR', 'OTHER'])
        .describe('취소 사유'),
    }),
  ),
  error: zod.unknown().nullable(),
});
