/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * 뭉치장 API
 * 유행 음식 공동구매 플랫폼 뭉치장의 API 명세입니다.

## 인증
로그인이 필요한 API는 `Authorization: Bearer {accessToken}` 헤더를 포함해야 합니다.

## 공통 응답 형식
모든 응답은 아래 구조를 따릅니다.
```json
{ "success": true, "data": { ... }, "error": null }
{ "success": false, "data": null, "error": { "code": "ERROR_CODE", "message": "설명", "detail": "상세" } }
```

 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

/**
 * 카카오 인가 코드로 로그인하거나 최초 가입 처리한다.
 * @summary 카카오 로그인 / 회원가입
 */
export const PostApiV1AuthKakaoBody = zod.object({
  authorizationCode: zod.string().describe('카카오 인가 코드'),
});

export const PostApiV1AuthKakaoResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    accessToken: zod.string(),
    refreshToken: zod.string(),
    isNewUser: zod.boolean().describe('최초 가입 여부'),
  }),
  error: zod.unknown().nullable(),
});

/**
 * @summary Access Token 갱신
 */
export const PostApiV1AuthRefreshBody = zod.object({
  refreshToken: zod.string(),
});

export const PostApiV1AuthRefreshResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    accessToken: zod.string(),
    refreshToken: zod.string(),
    isNewUser: zod.boolean().describe('최초 가입 여부'),
  }),
  error: zod.unknown().nullable(),
});

/**
 * Refresh Token을 무효화한다.
 * @summary 로그아웃
 */
export const PostApiV1AuthLogoutResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});

/**
 * @summary 내 정보 조회
 */
export const GetApiV1UsersMeResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    id: zod.number(),
    nickname: zod.string(),
    profileImageUrl: zod.string().nullable(),
  }),
  error: zod.unknown().nullable(),
});

/**
 * @summary 회원 탈퇴
 */
export const DeleteApiV1UsersMeResponse = zod.object({
  success: zod.boolean(),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
});
