/* /* eslint-disable *\/ */
/**
 * // @ts-nocheck
 * // This file is automatically generated by Orval.
 * // Do not edit it manually.
 */
import * as zod from 'zod';

/**
 * @summary 참여 목록 조회 (참여중 · 완료 · 환불 탭)
 */
export const getApiV1UsersMeParticipationsQueryStatusDefault = `ACTIVE`;
export const getApiV1UsersMeParticipationsQueryPageDefault = 0;
export const getApiV1UsersMeParticipationsQuerySizeDefault = 20;
export const getApiV1UsersMeParticipationsQuerySizeMax = 100;

export const GetApiV1UsersMeParticipationsQueryParams = zod.object({
  status: zod
    .enum(['ACTIVE', 'COMPLETED', 'REFUNDED'])
    .default(getApiV1UsersMeParticipationsQueryStatusDefault)
    .describe('ACTIVE=참여중 \/ COMPLETED=완료 \/ REFUNDED=환불내역'),
  page: zod.number().default(getApiV1UsersMeParticipationsQueryPageDefault),
  size: zod
    .number()
    .max(getApiV1UsersMeParticipationsQuerySizeMax)
    .default(getApiV1UsersMeParticipationsQuerySizeDefault),
});

export const GetApiV1UsersMeParticipationsResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    content: zod.array(
      zod.object({
        participationId: zod.number(),
        productName: zod.string(),
        storeName: zod.string(),
        pickupDate: zod.iso.date().nullable(),
        pickupTimeStart: zod.iso.time({}).nullable(),
        pickupTimeEnd: zod.iso.time({}).nullable(),
        paymentAmount: zod.number(),
        quantity: zod.number(),
        achievementRate: zod.number(),
        achievementStatus: zod.enum(['BEFORE_ACHIEVED', 'ACHIEVED']),
        dDay: zod.number(),
        groupBuyId: zod.number(),
        canCancel: zod.boolean(),
        canViewPickup: zod.boolean(),
        canViewQr: zod.boolean(),
      }),
    ),
    totalElements: zod.number(),
    totalPages: zod.number(),
  }),
  error: zod.unknown().nullable(),
});

/**
 * @summary 내 공구 요청 목록 조회 (개설 요청 내역 탭)
 */
export const GetApiV1UsersMeGroupBuyRequestsResponse = zod.object({
  success: zod.boolean(),
  data: zod.array(
    zod.object({
      requestId: zod.number(),
      storeName: zod.string(),
      productName: zod.string(),
      desiredQuantity: zod.number(),
      desiredPickupDate: zod.iso.date(),
      additionalNote: zod.string().nullish(),
      status: zod
        .enum(['SUBMITTED', 'IN_REVIEW', 'IN_CONTACT', 'OPENED', 'REJECTED'])
        .describe(
          'SUBMITTED=요청 접수 \/ IN_REVIEW=검토 중 \/ IN_CONTACT=매장 컨택 중 \/\nOPENED=공구 개설 완료 \/ REJECTED=개설 불가\n',
        ),
      rejectionReason: zod
        .string()
        .nullable()
        .describe('status=REJECTED 시 노출'),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  ),
  error: zod.unknown().nullable(),
});

/**
 * 참여중 · 완료 · 환불내역 · 개설요청 건수를 반환한다 (탭 칩 괄호 숫자용).
 * @summary 마이페이지 탭별 건수 조회
 */
export const GetApiV1UsersMeTabsCountsResponse = zod.object({
  success: zod.boolean(),
  data: zod.object({
    activeCount: zod.number().describe('참여중'),
    completedCount: zod.number().describe('완료'),
    refundedCount: zod.number().describe('환불내역'),
    requestCount: zod.number().describe('개설 요청 내역'),
  }),
  error: zod.unknown().nullable(),
});
