export interface RequestRegion {
  key: string;
  name: string;
}

export interface RequestCity {
  regionType: string;
  name: string;
  regions: RequestRegion[];
}

export const REQUEST_REGIONS_DATA: RequestCity[] = [
  {
    regionType: 'SEOUL',
    name: '서울',
    regions: [
      { key: 'SEOUL_GANGNAM', name: '강남' },
      { key: 'SEOUL_YEOKSAM', name: '역삼' },
      { key: 'SEOUL_SAMSEONG', name: '삼성' },
      { key: 'SEOUL_SINSA', name: '신사' },
      { key: 'SEOUL_APGUJEONG', name: '압구정' },
      { key: 'SEOUL_CHEONGDAM', name: '청담' },
      { key: 'SEOUL_SEOCHO', name: '서초' },
      { key: 'SEOUL_BANGBAE', name: '방배' },
      { key: 'SEOUL_GYODAE', name: '교대' },
      { key: 'SEOUL_JAMSIL', name: '잠실' },
      { key: 'SEOUL_SINCHEON', name: '신천' },
      { key: 'SEOUL_SONGPA', name: '송파' },
      { key: 'SEOUL_JONGNO', name: '종로' },
      { key: 'SEOUL_JUNGGU', name: '중구' },
      { key: 'SEOUL_EULJIRO', name: '을지로' },
      { key: 'SEOUL_MYEONGDONG', name: '명동' },
      { key: 'SEOUL_HONGDAE', name: '홍대' },
      { key: 'SEOUL_HAPJEONG', name: '합정' },
      { key: 'SEOUL_SANGSU', name: '상수' },
      { key: 'SEOUL_MAPO', name: '마포' },
      { key: 'SEOUL_SEONGSU', name: '성수' },
      { key: 'SEOUL_GEONDAE', name: '건대' },
      { key: 'SEOUL_GWANGJIN', name: '광진' },
      { key: 'SEOUL_ITAEWON', name: '이태원' },
      { key: 'SEOUL_HANNAM', name: '한남' },
      { key: 'SEOUL_YONGSAN', name: '용산' },
      { key: 'SEOUL_YEONGDEUNGPO', name: '영등포' },
      { key: 'SEOUL_YEOUIDO', name: '여의도' },
      { key: 'SEOUL_NOWON', name: '노원' },
      { key: 'SEOUL_DOBONG', name: '도봉' },
      { key: 'SEOUL_GANGBUK', name: '강북' },
    ],
  },
  {
    regionType: 'GYEONGGI',
    name: '경기',
    regions: [
      { key: 'GYEONGGI_SUWON', name: '수원' },
      { key: 'GYEONGGI_YEONGTONG', name: '영통' },
      { key: 'GYEONGGI_PALDAL', name: '팔달' },
      { key: 'GYEONGGI_SEONGNAM', name: '성남' },
      { key: 'GYEONGGI_BUNDANG', name: '분당' },
      { key: 'GYEONGGI_PANGYO', name: '판교' },
      { key: 'GYEONGGI_GOYANG', name: '고양' },
      { key: 'GYEONGGI_ILSAN', name: '일산' },
      { key: 'GYEONGGI_YONGIN', name: '용인' },
      { key: 'GYEONGGI_SUJI', name: '수지' },
      { key: 'GYEONGGI_GIHEUNG', name: '기흥' },
      { key: 'GYEONGGI_BUCHEON', name: '부천' },
      { key: 'GYEONGGI_JUNGDONG', name: '중동' },
      { key: 'GYEONGGI_SANGDONG', name: '상동' },
      { key: 'GYEONGGI_ANSAN', name: '안산' },
      { key: 'GYEONGGI_DANWON', name: '단원' },
      { key: 'GYEONGGI_SANGROK', name: '상록' },
      { key: 'GYEONGGI_NAMYANGJU', name: '남양주' },
      { key: 'GYEONGGI_DASAN', name: '다산' },
      { key: 'GYEONGGI_BYEOLNAE', name: '별내' },
      { key: 'GYEONGGI_ANYANG', name: '안양' },
      { key: 'GYEONGGI_PYEONGCHON', name: '평촌' },
      { key: 'GYEONGGI_BEOMGYE', name: '범계' },
      { key: 'GYEONGGI_HWASEONG', name: '화성' },
      { key: 'GYEONGGI_DONGTAN', name: '동탄' },
      { key: 'GYEONGGI_PAJU', name: '파주' },
      { key: 'GYEONGGI_UNJEONG', name: '운정' },
    ],
  },
  {
    regionType: 'INCHEON',
    name: '인천',
    regions: [
      { key: 'INCHEON_SONGDO', name: '송도' },
      { key: 'INCHEON_YEONSU', name: '연수' },
      { key: 'INCHEON_GUWOL', name: '구월' },
      { key: 'INCHEON_NAMDONG', name: '남동' },
      { key: 'INCHEON_BUPYEONG', name: '부평' },
      { key: 'INCHEON_GYEYANG', name: '계양' },
      { key: 'INCHEON_CHEONGNA', name: '청라' },
      { key: 'INCHEON_SEOGU', name: '서구' },
      { key: 'INCHEON_JUAN', name: '주안' },
      { key: 'INCHEON_MICHUHOL', name: '미추홀' },
      { key: 'INCHEON_YEONGJONGDO', name: '영종도' },
      { key: 'INCHEON_JUNGGU', name: '중구' },
    ],
  },
  {
    regionType: 'GANGWON',
    name: '강원',
    regions: [
      { key: 'GANGWON_CHUNCHEON', name: '춘천' },
      { key: 'GANGWON_WONJU', name: '원주' },
      { key: 'GANGWON_GANGNEUNG', name: '강릉' },
      { key: 'GANGWON_SOKCHO', name: '속초' },
      { key: 'GANGWON_YANGYANG', name: '양양' },
      { key: 'GANGWON_DONGHAE', name: '동해' },
      { key: 'GANGWON_SAMCHEOK', name: '삼척' },
    ],
  },
  {
    regionType: 'DAEJEON',
    name: '대전',
    regions: [
      { key: 'DAEJEON_DUNSAN', name: '둔산' },
      { key: 'DAEJEON_SEOGU', name: '서구' },
      { key: 'DAEJEON_EUNHAENG', name: '은행' },
      { key: 'DAEJEON_DAEHEUNG', name: '대흥' },
      { key: 'DAEJEON_JUNGGU', name: '중구' },
      { key: 'DAEJEON_YUSEONG', name: '유성' },
      { key: 'DAEJEON_DOAN', name: '도안' },
      { key: 'DAEJEON_DONGGU', name: '동구' },
      { key: 'DAEJEON_DAEDEOK', name: '대덕' },
    ],
  },
  {
    regionType: 'SEJONG',
    name: '세종',
    regions: [{ key: 'SEJONG_SEJONG', name: '세종' }],
  },
  {
    regionType: 'CHUNGNAM',
    name: '충남',
    regions: [
      { key: 'CHUNGNAM_CHEONAN', name: '천안' },
      { key: 'CHUNGNAM_SINBU', name: '신부' },
      { key: 'CHUNGNAM_DUJEONG', name: '두정' },
      { key: 'CHUNGNAM_ASAN', name: '아산' },
      { key: 'CHUNGNAM_TANGJEONG', name: '탕정' },
      { key: 'CHUNGNAM_DANGJIN', name: '당진' },
      { key: 'CHUNGNAM_SEOSAN', name: '서산' },
      { key: 'CHUNGNAM_GYERYONG', name: '계룡' },
      { key: 'CHUNGNAM_NONSAN', name: '논산' },
    ],
  },
  {
    regionType: 'CHUNGBUK',
    name: '충북',
    regions: [
      { key: 'CHUNGBUK_CHEONGJU', name: '청주' },
      { key: 'CHUNGBUK_SANGDANG', name: '상당' },
      { key: 'CHUNGBUK_HEUNGDEOK', name: '흥덕' },
      { key: 'CHUNGBUK_CHUNGJU', name: '충주' },
      { key: 'CHUNGBUK_JECHEON', name: '제천' },
      { key: 'CHUNGBUK_EUMSEONG', name: '음성' },
      { key: 'CHUNGBUK_JINCHEON', name: '진천' },
    ],
  },
  {
    regionType: 'BUSAN',
    name: '부산',
    regions: [
      { key: 'BUSAN_SEOMYEON', name: '서면' },
      { key: 'BUSAN_JEONPO', name: '전포' },
      { key: 'BUSAN_JINGU', name: '진구' },
      { key: 'BUSAN_HAEUNDAE', name: '해운대' },
      { key: 'BUSAN_CENTUM', name: '센텀' },
      { key: 'BUSAN_MARINE_CITY', name: '마린시티' },
      { key: 'BUSAN_GWANGALLI', name: '광안리' },
      { key: 'BUSAN_SUYEONG', name: '수영' },
      { key: 'BUSAN_NAMCHEON', name: '남천' },
      { key: 'BUSAN_NAMPO', name: '남포' },
      { key: 'BUSAN_JUNGGU', name: '중구' },
      { key: 'BUSAN_YEONGDO', name: '영도' },
      { key: 'BUSAN_DONGRAE', name: '동래' },
      { key: 'BUSAN_YEONSAN', name: '연산' },
      { key: 'BUSAN_BUSANDAE', name: '부산대' },
      { key: 'BUSAN_SAHA', name: '사하' },
      { key: 'BUSAN_HADAN', name: '하단' },
    ],
  },
  {
    regionType: 'ULSAN',
    name: '울산',
    regions: [
      { key: 'ULSAN_SAMSAN', name: '삼산' },
      { key: 'ULSAN_DALDONG', name: '달동' },
      { key: 'ULSAN_NAMGU', name: '남구' },
      { key: 'ULSAN_SEONGNAM', name: '성남' },
      { key: 'ULSAN_JUNGGU', name: '중구' },
      { key: 'ULSAN_DONGGU', name: '동구' },
      { key: 'ULSAN_BUKGU', name: '북구' },
      { key: 'ULSAN_ULJU', name: '울주' },
    ],
  },
  {
    regionType: 'GYEONGNAM',
    name: '경남',
    regions: [
      { key: 'GYEONGNAM_CHANGWON', name: '창원' },
      { key: 'GYEONGNAM_SANGNAM', name: '상남' },
      { key: 'GYEONGNAM_UICHANG', name: '의창' },
      { key: 'GYEONGNAM_GIMHAE', name: '김해' },
      { key: 'GYEONGNAM_YANGSAN', name: '양산' },
      { key: 'GYEONGNAM_JINJU', name: '진주' },
      { key: 'GYEONGNAM_GEOJE', name: '거제' },
      { key: 'GYEONGNAM_TONGYEONG', name: '통영' },
    ],
  },
  {
    regionType: 'GYEONGBUK',
    name: '경북',
    regions: [
      { key: 'GYEONGBUK_POHANG', name: '포항' },
      { key: 'GYEONGBUK_GYEONGJU', name: '경주' },
      { key: 'GYEONGBUK_HWANGRIDAN_GIL', name: '황리단길' },
      { key: 'GYEONGBUK_GUMI', name: '구미' },
      { key: 'GYEONGBUK_GYEONGSAN', name: '경산' },
      { key: 'GYEONGBUK_ANDONG', name: '안동' },
    ],
  },
  {
    regionType: 'DAEGU',
    name: '대구',
    regions: [
      { key: 'DAEGU_DONGSEONGNO', name: '동성로' },
      { key: 'DAEGU_JUNGGU', name: '중구' },
      { key: 'DAEGU_SUSEONGGU', name: '수성구' },
      { key: 'DAEGU_BEOMEO', name: '범어' },
      { key: 'DAEGU_SANGIN', name: '상인' },
      { key: 'DAEGU_DALSEO', name: '달서' },
      { key: 'DAEGU_CHILGOK', name: '칠곡' },
      { key: 'DAEGU_BUKGU', name: '북구' },
      { key: 'DAEGU_DONGGU', name: '동구' },
    ],
  },
  {
    regionType: 'GWANGJU',
    name: '광주',
    regions: [
      { key: 'GWANGJU_SANGMU_JIGU', name: '상무지구' },
      { key: 'GWANGJU_CHIPYEONG', name: '치평' },
      { key: 'GWANGJU_SEOGU', name: '서구' },
      { key: 'GWANGJU_DONGMYEONGDONG', name: '동명동' },
      { key: 'GWANGJU_CHUNGJANGRO', name: '충장로' },
      { key: 'GWANGJU_DONGGU', name: '동구' },
      { key: 'GWANGJU_SUWAN', name: '수완' },
      { key: 'GWANGJU_CHEOMDAN', name: '첨단' },
      { key: 'GWANGJU_GWANGSANGU', name: '광산구' },
      { key: 'GWANGJU_BONGSEON', name: '봉선' },
      { key: 'GWANGJU_NAMGU', name: '남구' },
      { key: 'GWANGJU_BUKGU', name: '북구' },
    ],
  },
  {
    regionType: 'JEONNAM',
    name: '전남',
    regions: [
      { key: 'JEONNAM_YEOSU', name: '여수' },
      { key: 'JEONNAM_SUNCHEON', name: '순천' },
      { key: 'JEONNAM_MOKPO', name: '목포' },
      { key: 'JEONNAM_NAMAK', name: '남악' },
      { key: 'JEONNAM_NAJU', name: '나주' },
    ],
  },
  {
    regionType: 'JEONBUK',
    name: '전북',
    regions: [
      { key: 'JEONBUK_JEONJU', name: '전주' },
      { key: 'JEONBUK_GAEKRIDANGIL', name: '객리단길' },
      { key: 'JEONBUK_WANSAN', name: '완산' },
      { key: 'JEONBUK_IKSAN', name: '익산' },
      { key: 'JEONBUK_GUNSAN', name: '군산' },
    ],
  },
  {
    regionType: 'JEJU',
    name: '제주',
    regions: [
      { key: 'JEJU_JEJU_SI', name: '제주시' },
      { key: 'JEJU_AEWOL', name: '애월' },
      { key: 'JEJU_HALLIM', name: '한림' },
      { key: 'JEJU_JOCHEON', name: '조천' },
      { key: 'JEJU_GUJWA', name: '구좌' },
      { key: 'JEJU_SEOGWIPO_SI', name: '서귀포시' },
      { key: 'JEJU_JUNGMUN', name: '중문' },
      { key: 'JEJU_ANDEOK', name: '안덕' },
      { key: 'JEJU_SEONGSAN', name: '성산' },
      { key: 'JEJU_PYOSEON', name: '표선' },
    ],
  },
];
