import fs from 'fs';
import path from 'path';

const GENERATED_DIR = path.join(process.cwd(), 'src/api/generated');
const OUTPUT_FILE = path.join(GENERATED_DIR, 'index.msw.ts');

function generateMswIndex() {
  if (!fs.existsSync(GENERATED_DIR)) {
    console.error('Generated directory not found:', GENERATED_DIR);
    return;
  }

  const files: string[] = [];

  function walk(dir: string) {
    const list = fs.readdirSync(dir);
    list.forEach((file) => {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat && stat.isDirectory()) {
        walk(fullPath);
      } else if (
        (file.endsWith('.msw.ts') || file === 'api.ts') &&
        file !== 'index.msw.ts'
      ) {
        files.push(fullPath);
      }
    });
  }

  walk(GENERATED_DIR);

  const imports: string[] = [];
  const handlerNames: string[] = [];

  files.forEach((file) => {
    const relativePath = path
      .relative(GENERATED_DIR, file)
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '');

    const content = fs.readFileSync(file, 'utf8');

    // orval이 생성하는 핸들러 함수: get{HttpMethod}ApiV1...MockHandler
    // mode: 'single'(api.ts)과 mode: 'tags-split'(.msw.ts) 모두 지원
    const mockFunctions = content.match(
      /export const (get[A-Z]\w+MockHandler) = /g,
    );

    if (mockFunctions) {
      const funcNames = mockFunctions.map((f) =>
        f.replace('export const ', '').replace(' = ', ''),
      );
      imports.push(
        `import { ${funcNames.join(', ')} } from './${relativePath}';`,
      );
      // 각 핸들러는 단일 MSW RequestHandler를 반환하므로 spread 없이 배열 원소로 추가
      funcNames.forEach((name) => handlerNames.push(`${name}()`));
    }
  });

  const output = `/**
 * Generated by scripts/generate-msw-index.ts
 * Do not edit manually.
 */
${imports.join('\n')}

export const generatedHandlers = [
  ${handlerNames.join(',\n  ')}
];
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✅ Generated MSW index: ${handlerNames.length}개 핸들러`);
}

generateMswIndex();
