import fs from 'fs';
import path from 'path';

const GENERATED_DIR = path.join(process.cwd(), 'src/api/generated');
const OUTPUT_FILE = path.join(GENERATED_DIR, 'index.msw.ts');

function generateMswIndex() {
  if (!fs.existsSync(GENERATED_DIR)) {
    console.error('Generated directory not found:', GENERATED_DIR);
    return;
  }

  const files: string[] = [];

  function walk(dir: string) {
    const list = fs.readdirSync(dir);
    list.forEach((file) => {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat && stat.isDirectory()) {
        walk(fullPath);
      } else if (file.endsWith('.msw.ts') && file !== 'index.msw.ts') {
        files.push(fullPath);
      }
    });
  }

  walk(GENERATED_DIR);

  const imports: string[] = [];
  const handlerNames: string[] = [];

  files.forEach((file, index) => {
    const relativePath = path
      .relative(GENERATED_DIR, file)
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '');

    // 파일 내용에서 'get...Mock' 혹은 '...Mock'으로 끝나는 함수 이름 추출 (Orval 컨벤션)
    const content = fs.readFileSync(file, 'utf8');
    const mockFunctions = content.match(/export const (get\w+Mock) = \(\) =>/g);

    if (mockFunctions) {
      const funcNames = mockFunctions.map((f) =>
        f.replace('export const ', '').replace(' = () =>', ''),
      );
      const alias = `handlers${index}`;
      imports.push(
        `import { ${funcNames.join(', ')} } from './${relativePath}';`,
      );
      funcNames.forEach((name) => handlerNames.push(`...${name}()`));
    }
  });

  const output = `/**
 * Generated by scripts/generate-msw-index.ts
 * Do not edit manually.
 */
${imports.join('\n')}

export const generatedHandlers = [
  ${handlerNames.join(',\n  ')}
];
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log('✅ Generated MSW index at:', OUTPUT_FILE);
}

generateMswIndex();
