#!/usr/bin/env tsx
/**
 * Orval이 생성한 .msw.ts 파일들을 파싱해서 GET 핸들러의
 * URL 패턴과 응답 팩토리 함수를 추출하고,
 * 정적 레지스트리에서 사용할 index.static.ts를 자동 생성합니다.
 *
 * 사용법: npm run generate (generate 스크립트에 포함됨)
 */

import fs from 'fs';
import path from 'path';

const GENERATED_DIRECTORY_PATH = path.join(process.cwd(), 'src/api/generated');
const OUTPUT_FILE_PATH = path.join(GENERATED_DIRECTORY_PATH, 'index.static.ts');

interface StaticMockEntry {
  urlPattern: string;
  responseFactoryFunctionName: string;
  importFilePath: string;
}

function findMockServiceWorkerFilePaths(directoryPath: string): string[] {
  const filePaths: string[] = [];

  for (const directoryEntry of fs.readdirSync(directoryPath, {
    withFileTypes: true,
  })) {
    const fullPath = path.join(directoryPath, directoryEntry.name);
    if (directoryEntry.isDirectory()) {
      filePaths.push(...findMockServiceWorkerFilePaths(fullPath));
    } else if (
      (directoryEntry.name.endsWith('.msw.ts') ||
        directoryEntry.name === 'api.ts') &&
      directoryEntry.name !== 'index.msw.ts' &&
      directoryEntry.name !== 'index.static.ts'
    ) {
      filePaths.push(fullPath);
    }
  }

  return filePaths;
}

function extractGetHandlerEntries(
  mockServiceWorkerFilePath: string,
): StaticMockEntry[] {
  const fileContent = fs.readFileSync(mockServiceWorkerFilePath, 'utf-8');
  const extractedEntries: StaticMockEntry[] = [];

  // Orval GET 핸들러 패턴:
  // export const getGet[Path]MockHandler = ... http.get('[url]', ...
  // 핸들러 함수명이 getGet으로 시작하는 것만 GET 메서드 핸들러
  const getHandlerWithUrlPattern =
    /export const (getGet\w+MockHandler)\b[\s\S]*?http\.get\(\s*'([^']+)'/g;

  let regexMatch: RegExpExecArray | null;
  while ((regexMatch = getHandlerWithUrlPattern.exec(fileContent)) !== null) {
    const handlerFunctionName = regexMatch[1];
    const rawUrlPattern = regexMatch[2];

    // */api/v1/path → /api/v1/path (와일드카드 제거)
    const urlPattern = rawUrlPattern.replace(/^\*/, '');

    // getGet[Path]MockHandler → getGet[Path]ResponseMock
    const responseFactoryFunctionName = handlerFunctionName.replace(
      'MockHandler',
      'ResponseMock',
    );

    // 응답 팩토리 함수가 실제로 파일에 존재하는지 검증
    if (!fileContent.includes(`export const ${responseFactoryFunctionName}`)) {
      console.warn(
        `[generate-static-registry] 건너뜀: ${responseFactoryFunctionName} 이 ${path.basename(mockServiceWorkerFilePath)} 에 없음`,
      );
      continue;
    }

    const relativeImportPath =
      './' +
      path
        .relative(GENERATED_DIRECTORY_PATH, mockServiceWorkerFilePath)
        .replace(/\\/g, '/')
        .replace(/\.ts$/, '');

    extractedEntries.push({
      urlPattern,
      responseFactoryFunctionName,
      importFilePath: relativeImportPath,
    });
  }

  return extractedEntries;
}

function generateStaticRegistryFile(): void {
  if (!fs.existsSync(GENERATED_DIRECTORY_PATH)) {
    console.error(
      '[generate-static-registry] generated 폴더를 찾을 수 없습니다:',
      GENERATED_DIRECTORY_PATH,
    );
    process.exit(1);
  }

  const allMockServiceWorkerFilePaths = findMockServiceWorkerFilePaths(
    GENERATED_DIRECTORY_PATH,
  );
  const allStaticMockEntries: StaticMockEntry[] = [];

  for (const filePath of allMockServiceWorkerFilePaths) {
    allStaticMockEntries.push(...extractGetHandlerEntries(filePath));
  }

  // 파일 경로별로 import할 함수명 묶기
  const functionNamesByImportPath = new Map<string, Set<string>>();
  for (const entry of allStaticMockEntries) {
    if (!functionNamesByImportPath.has(entry.importFilePath)) {
      functionNamesByImportPath.set(entry.importFilePath, new Set());
    }
    functionNamesByImportPath
      .get(entry.importFilePath)!
      .add(entry.responseFactoryFunctionName);
  }

  const outputLines: string[] = [
    '/**',
    ' * Generated by scripts/generate-static-registry.ts',
    ' * Do not edit manually.',
    ' */',
    '',
  ];

  for (const [importFilePath, functionNames] of functionNamesByImportPath) {
    outputLines.push(
      `import { ${[...functionNames].join(', ')} } from '${importFilePath}';`,
    );
  }

  outputLines.push('');
  outputLines.push('export interface StaticMockEntry {');
  outputLines.push('  urlPattern: string;');
  outputLines.push('  getResponseData: () => unknown;');
  outputLines.push('}');
  outputLines.push('');
  outputLines.push(
    'export const generatedStaticMockEntries: StaticMockEntry[] = [',
  );

  for (const entry of allStaticMockEntries) {
    outputLines.push(
      `  { urlPattern: '${entry.urlPattern}', getResponseData: ${entry.responseFactoryFunctionName} },`,
    );
  }

  outputLines.push('];');

  fs.writeFileSync(OUTPUT_FILE_PATH, outputLines.join('\n'), 'utf-8');
  console.log(
    `✅ Generated static registry: ${allStaticMockEntries.length}개 GET 엔드포인트`,
  );
}

generateStaticRegistryFile();
